# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9318aada454daea1d925d841e1f6a70cce95d291c061d5d8aa190e625269f333dccd51a8a6fd152751e6cca71dba6c476d4a80e5a464cf06aa8987492a06c698

test:
  secret_key_base: 4565ebab3938ade7567dce0f12613664696ba3bee68ecffcd6a807513e68107bd5d0d1491b6314d737c0a7a426c3f4eedede320f51a549bc2a5ea6bebced289b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
